### ISSUE TITLE
Infinite rendering on state update inside callbacks

### ISSUE THREAD

**Issue by Ashersam** [friendsofagape/usfm-editor#23]
### build tool
 Next.js

### Node.js version
 14.8.0

### Usfm Editor version
0.8.0-SNAPSHOT.5

### Reproduction repository
https://github.com/Ashersam/editor-demo/blob/master/src/App.js#L25

### Issue Description
We have updated our package to the latest from `0.8.0-SNAPSHOT.2` since we have use cases of single or multiple chapters render based on screen space and toolbar separation.
I have started implementing ChapterSelect based render and wrapped it up with the `withToolBar.js` component.

Things are working except whenever I update the state on the following callbacks (`onChange`, `onIdentificationChange`, `onVerseChange`) whatever changes I do just rerenders multiple times and comes to the original loaded state, sometimes it ends in an infinite loop. And most of these things works as expected in `0.8.0-SNAPSHOT.2`.

**Comment by aunger** [comment]
I showed how this can be solved in https://github.com/Ashersam/editor-demo/pull/1, and now with [usfm-editor 0.8.0](https://github.com/friendsofagape/usfm-editor/releases/tag/0.8.0), a related bug has been fixed that will allow you to drop `usememo`, and create the `CustomEditor` component outside of `App()`.
